### ISSUE TITLE
Deploy to S3

### ISSUE THREAD

**Issue by jbhannah** [jbhannah/jbhannah.net#8]
Have Travis CI [deploy to S3](http://docs.travis-ci.com/user/deployment/s3/) on successful build of `master`.

```yaml
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: jbhannah.net
  region: us-east-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
```

- [x] Configure Travis
- [x] Remove GitHub Pages (`CNAME`, `.nojekyll`) files
